language: cpp
sudo: required
dist: trusty

matrix:
    include:
        - os: linux
          addons:
            apt:
              packages:
              - libfreeimage-dev
              - libftgl-dev
              - libsfml-dev
              - libfluidsynth-dev
              - libgtk-3-dev
              - gcc-4.4
          compiler: gcc-4.4
          #gcc-4.4 (Ubuntu/Linaro 4.4.7-8ubuntu1) 4.4.7
        - os: linux
          addons:
            apt:
              packages:
              - libfreeimage-dev
              - libftgl-dev
              - libsfml-dev
              - libfluidsynth-dev
              - libgtk-3-dev
              - gcc-4.6
          compiler: gcc-4.6
          #gcc-4.6 (Ubuntu/Linaro 4.6.4-6ubuntu2) 4.6.4
        - os: linux
          addons:
            apt:
              packages:
              - libfreeimage-dev
              - libftgl-dev
              - libsfml-dev
              - libfluidsynth-dev
              - libgtk-3-dev
              - gcc-4.7
          compiler: gcc-4.7
          #gcc-4.7
        - os: linux
          compiler: gcc
          #gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
        - os: linux
          addons:
            apt:
              sources:
              - ubuntu-toolchain-r-test
              packages:
              - libfreeimage-dev
              - libftgl-dev
              - libsfml-dev
              - libfluidsynth-dev
              - libgtk-3-dev
              - gcc-4.8
          compiler: gcc-4.8
          #gcc-4.8 (Ubuntu 4.8.5-2ubuntu1~14.04.1) 4.8.5
        - os: linux
          addons:
            apt:
              sources:
              - ubuntu-toolchain-r-test
              packages:
              - libgtk2.0-dev
              - libftgl-dev
              - libsfml-dev
              - libfluidsynth-dev
              - libgtk-3-dev
              - gcc-4.9
          compiler: gcc-4.9
          #gcc-4.9 (Ubuntu 4.9.3-8ubuntu2~14.04) 4.9.3
        - os: linux
          addons:
            apt:
              sources:
              - ubuntu-toolchain-r-test
              packages:
              - libfreeimage-dev
              - libftgl-dev
              - libsfml-dev
              - libfluidsynth-dev
              - libgtk-3-dev
              - gcc-5
          compiler: gcc-5
          #gcc-5 (Ubuntu 5.3.0-3ubuntu1~14.04) 5.3.0 20151204
        - os: linux
          addons:
            apt:
              sources:
              - ubuntu-toolchain-r-test
              packages:
              - libfreeimage-dev
              - libftgl-dev
              - libsfml-dev
              - libfluidsynth-dev
              - libgtk-3-dev
              - gcc-6
          compiler: gcc-6
          env: WFLAGS="-Wno-tautological-compare"
          #gcc-6 (Ubuntu 6.1.1-3ubuntu11~14.04.1) 6.1.1 20160511
        - os: linux
          compiler: clang
          #clang version 3.5.0 (tags/RELEASE_350/final)
        - os: linux
          addons:
            apt:
              sources:
              - llvm-toolchain-precise-3.5
              packages:
              - libfreeimage-dev
              - libftgl-dev
              - libsfml-dev
              - libfluidsynth-dev
              - libgtk-3-dev
              - clang-3.5
          compiler: clang-3.5
          #Ubuntu clang version 3.5.0-4ubuntu2~trusty2 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
        - os: linux
          addons:
            apt:
              sources:
              - llvm-toolchain-precise-3.6
              - ubuntu-toolchain-r-test
              packages:
              - libfreeimage-dev
              - libftgl-dev
              - libsfml-dev
              - libfluidsynth-dev
              - libgtk-3-dev
              - clang-3.6
          compiler: clang-3.6
          #Ubuntu clang version 3.6.2-svn240577-1~exp1 (branches/release_36) (based on LLVM 3.6.2)
        - os: linux
          addons:
            apt:
              sources:
              - llvm-toolchain-precise-3.7
              - ubuntu-toolchain-r-test
              packages:
              - libfreeimage-dev
              - libftgl-dev
              - libsfml-dev
              - libfluidsynth-dev
              - libgtk-3-dev
              - clang-3.7
          compiler: clang-3.7
          #Ubuntu clang version 3.7.1-svn253571-1~exp1 (branches/release_37) (based on LLVM 3.7.1)
        - os: linux
          addons:
            apt:
              sources:
              - llvm-toolchain-precise-3.8
              - ubuntu-toolchain-r-test
              packages:
              - libfreeimage-dev
              - libftgl-dev
              - libsfml-dev
              - libfluidsynth-dev
              - libgtk-3-dev
              - clang-3.8
          compiler: clang-3.8
          #clang version 3.8.1-svn271127-1~exp1 (branches/release_38)
#        - os: osx
#          osx_image: beta-xcode6.1
#          #Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
#        - os: osx
#          osx_image: beta-xcode6.2
#          compiler: gcc
#          #Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
##        - os: osx
##          osx_image: beta-xcode6.3
##          #I think xcode.6.3 VM is broken, it does not boot
#        - os: osx
#          osx_image: xcode6.4
#          #Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
#        - os: osx
#          osx_image: xcode7
#          #Apple LLVM version 7.0.0 (clang-700.0.72)
#        - os: osx
#          osx_image: xcode7.1
#          #Apple LLVM version 7.0.0 (clang-700.1.76)
#        - os: osx
#          osx_image: xcode7.2
#          #Apple LLVM version 7.0.2 (clang-700.1.81)
        - os: osx
          osx_image: xcode7.3
          #Apple LLVM version 7.3.0 (clang-703.0.31)
    allow_failures:
      - compiler: clang-3.5
      - compiler: clang-3.6
      - compiler: clang-3.7
      - compiler: clang-3.8

cache:
  apt: true
  ccache: true
  directories:
  - $HOME/slade_cache

addons:
  apt:
    packages:
    - libfreeimage-dev
    - libftgl-dev
    - libsfml-dev
    - libfluidsynth-dev
    - libgtk-3-dev
before_script:
  - git clone https://github.com/wxWidgets/wxWidgets.git
  - mkdir buildgtk
  - cd buildgtk
  - ../configure --with-gtk --enable-mediactrl --enable-webview
  - make
  - make install
  - ldconfig
  - cd ..
  - export CFLAGS="-Wall -W -Werror $WFLAGS"
  - export CCACHE_COMPRESS=true
  - cmake .. -DCMAKE_BUILD_TYPE=Release

script: make -k
